using System.Text.Json.Serialization;

namespace WebAppBackend.Api.Models;

/// <summary>
/// Maps to one button in the Angular left-hand navigation panel and one element in the central column, except for the divider type, which is only a visual separator.
/// </summary>
public class ContentSection
{
	/// <summary> Stable identifier used for deep-linking / scrolling. </summary>
	public string? Id { get; set; } = string.Empty;

	/// <summary> Sequence number. </summary>
	/// <remarks>Generated by the getter => Removes the need for an "order" attribute in the XML, and also removes the need to validate another attribute.</remarks>
	public int Order { get; set; }

	///<summary> For when the title on the content section is too long. Optional. </summary> 
	[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
	public string? Description { get; set; }
	///<summary> Text for the button and central column. </summary> 
	public string? Title { get; set; }

	/// <summary>
	/// Raw (X)HTML markup for the body of the panel, taken verbatim from the
	/// XML file's &lt;Content&gt; element wrapped in CDATA.
	/// </summary>
	public string Html { get; set; } = string.Empty;

	[JsonConverter(typeof(JsonStringEnumConverter))]
	public SectionType Type { get; set; } = SectionType.Expansion;

	public static SectionType TextToType(string? xmlAttribute)
	{
		return Enum.TryParse<SectionType>(xmlAttribute, true, out var result)
			? result
			: SectionType.Expansion;
	}

	/// <summary> Type of section.
	/// Default are expansion panels.
	/// Header is a &lt;H1&gt;.
	/// Divider is a splitting line with no text. </summary>
	public enum SectionType
	{
		Divider,
		Expansion,
		Header,
	}

}

/// <summary> Alias class for better readability. ValidationResults are the output of the validation process, and are written to error-state.xml.
/// </summary>
/// <remarks> ContentSections are meant to flexible, today and in the future. That's why there's a validation process.<br/>
/// ValidationResults, on the other hand, are hard coded ad-hoc. To prevent accidental bugs, all fields are required.</remarks>
public class ValidationResult : ContentSection
{
	new public required string Id { get; set; }
	new public required int Order { get; set; }
	new public required string Description { get; set; }
	new public required string Title { get; set; }
	new public required string Html { get; set; }
}