using System.Text.Json;
using System.Text.Json.Serialization;

namespace WebAppBackend.Api.Models;

/// <summary>
/// Maps to one button in the Angular left-hand navigation panel and one element in the central column, except for the divider type, which is only a visual separator.
/// </summary>
public class ContentSection
{
	/// <summary> Stable identifier used for deep-linking / scrolling. </summary>
	public virtual string? Id { get; set; } = string.Empty;

	/// <summary> Sequence number. </summary>
	/// <remarks>Generated by the getter => Removes the need for an "order" attribute in the XML, and also removes the need to validate another attribute.</remarks>
	public virtual int Order { get; set; }

	///<summary> For when the title on the content section is too long. Optional. </summary> 
	[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
	public virtual string? Description { get; set; }
	///<summary> Text for the button and central column. </summary> 
	public virtual string? Title { get; set; }

	/// <summary> Raw (X)HTML markup for the body of the panel, taken verbatim from the XML file's &lt;Content&gt; element wrapped in CDATA. </summary>
	public virtual string Html { get; set; } = string.Empty;

	[JsonConverter(typeof(CamelCaseStringEnumConverter))]
	public SectionType Type { get; set; } = SectionType.Expansion;

	public static SectionType TextToType(string? xmlAttribute)
	{
		return Enum.TryParse<SectionType>(xmlAttribute, true, out var result)
			? result
			: SectionType.Expansion;
	}

	/// <summary> Type of section.
	/// Default are expansion panels.
	/// Header is a &lt;H1&gt;.
	/// Divider is a splitting line with no text. </summary>
	public enum SectionType
	{
		Divider,
		Expansion,
		Header,
		Setup,
	}
	public class CamelCaseStringEnumConverter() : JsonStringEnumConverter(JsonNamingPolicy.CamelCase) { }
}