using WebAppBackend.Api.Models;

namespace WebAppBackend.Api.Validation
{
	public class ContentValidator
	{
		public List<ContentSection> Validate(List<ContentSection>? sections )
		{
			List<ContentSection> errorState = new List<ContentSection>();
			HashSet<string> ids = new HashSet<string>();
			HashSet<string> titles = new HashSet<string>();

			if (sections == null || sections.Count == 0)
			{
				errorState.Add(
				new ContentSection
				{
					Order = 1,
					Title = "No sections found",
					Description = "The content has no sections defined.",
					Html = "The content has no sections defined."
				});
				return errorState;
			}

			foreach (var section in sections)
			{
				// Dividers only need the number generated by the getter, and should not have an Id, since it's used for tracking and has a cost in JS.
				if (section.Type == SectionType.Divider)
				{
					if (!string.IsNullOrEmpty(section.Id))
					{
						errorState.Add(new ContentSection
						{
							Order = errorState.Count + 1,
							Title = $"Section nr {section.Order} Divider has Id!",
							Description = $"Section number {section.Order} is a Divider but has an Id attribute: '{section.Id}'",
							Html = $$"""Section number {{section.Order}} is a Divider but has an Id attribute: '{{section.Id}}'"""
						});
					}
				}
				else
				{
					ValidateAttribute(section, section.Id, nameof(ContentSection.Id), section.Title, nameof(ContentSection.Title), ids, errorState);
					ValidateAttribute(section, section.Title, nameof(ContentSection.Title), section.Id, nameof(ContentSection.Id), titles, errorState);
				}

			}
			return errorState;
		}

		/// <summary>
		/// Checks the presence / uniqueness of either Id or Title attributes. Uses the other attribute for reference in the error message.
		/// </summary>
		private void ValidateAttribute(
			ContentSection section,
			string? thisValue,
			string thisAttributeName,
			string? otherAttributeValue,
			string otherAttributeName,
			HashSet<string> seenValues,
			List<ContentSection> errorState)
		{
			string insert = string.IsNullOrWhiteSpace(otherAttributeValue) ? "" : $" - {otherAttributeName}: '{otherAttributeValue}'";
			string additionalInfo = insert + (string.IsNullOrWhiteSpace(section.Description) ? "" : $", description: '{section.Description}'");

			if (thisValue == null) // null means the attribute isn't just empty, it's not there.
			{
				errorState.Add(new ContentSection
				{
					Order = errorState.Count + 1,
					Title = $"Section nr {section.Order} missing '{thisAttributeName}'",
					Description = $"Section number {section.Order}{insert}: is missing the {thisAttributeName} attribute.",
					Html = $$"""Section number {{section.Order}}: {{additionalInfo}}"""
				});
			}
			else if (string.IsNullOrWhiteSpace(thisValue))
			{
				errorState.Add(new ContentSection
				{
					Order = errorState.Count + 1,
					Title = $"Section nr {section.Order} empty '{thisAttributeName}'",
					Description = $"Section number {section.Order}{insert}: has an empty {thisAttributeName} attribute.",
					Html = $$"""Section number {{section.Order}}: {{additionalInfo}}"""
				});
			}
			else if (!seenValues.Add(thisValue))
			{
				errorState.Add(new ContentSection
				{
					Order = errorState.Count + 1,
					Title = $"Section nr {section.Order} duplicate '{thisAttributeName}'",
					Description = $"Section number {section.Order}{insert}: has a duplicate {thisAttributeName} attribute: '{thisValue}'",
					Html = $$"""Section number {{section.Order}}: {{additionalInfo}}"""
				});
			}
		}
	}
}
