using WebAppBackend.Api.DataAccess;
using WebAppBackend.Api.Models;
namespace WebAppBackend.Api.Validation;

public class ContentValidator(IDataAccess dataAccess) : IContentValidator
{
	private readonly IDataAccess file = dataAccess;

	///<summary>Takes a series of <see cref="ContentSection"/> and validates them. Errors found in the XML file are saved to error-state.xml in the same folder as the site-content.xml file. <br/>
	///If no content errors are found, a timestamp is saved to validation-date.xml</summary>
	///<remarks>This method accepts ContentSections and will out ValidationResults. To prevent bad routing, it throws if it detects ValidationResults in sections (only during development)</remarks>
	///<returns>True if the validation process succeeded. False if an IO writing failure occurred.</returns>
	
	public bool TryValidate(IReadOnlyList<ContentSection> sections, out ValidationResult? criticalError)
	{
		List<ValidationResult> errorState = new List<ValidationResult>();
		HashSet<string> ids = new HashSet<string>();
		HashSet<string> titles = new HashSet<string>();

		if (!ClearValidation())
		{
			// Not being able to write to disk is a critical failure, validation aborted. 
			criticalError = new ValidationResult
			{
				Id = "error",
				Order = 1,
				Title = "Validation state / date could not be cleared",
				Description = "Either validation-state or validation-date could not be cleared. This may indicate a file system permission issue.",
				Html = "The validation state could not be cleared. This may indicate a file system permission issue. Check log."
			};
			return false;
		}

		if (sections == null || sections.Count == 0)
		{
			errorState.Add(new ValidationResult
			{
				Id = "error",
				Order = 1,
				Title = "No sections found",
				Description = "The content has no sections defined.",
				Html = "The content has no sections defined."
			});
			// Nothing else to validate, save and return.
			return TryStoreValidation(errorState, out criticalError);
		}

#if DEBUG // Won't happen from changing the XML, might happen during development: bad routing.
		if (sections.Any(x => x.GetType() == typeof(ValidationResult)))
			throw new ArgumentException("Bad Routing: sections argument must not contain ValidationResults!", nameof(sections));
#endif

		// First element of a content xml is always a setup section.
		if (sections.First().Type != ContentSection.SectionType.Setup)
		{
			errorState.Add(new ValidationResult
			{
				Id = "error_" + (errorState.Count + 1),
				Order = errorState.Count + 1,
				Title = $"Setup section missing!",
				Description = $"First section is not a setup section!",
				Html = $$"""First section must be a setup section!"""
			});
		}

		foreach (var section in sections)
		{
			// Dividers only need the number generated by the getter, and should not have an Id, since it's used for tracking and has a cost in JS.
			// Setup sections are also not tracked and shouldn't have an Id either
			if (section.Type == ContentSection.SectionType.Divider || section.Type == ContentSection.SectionType.Setup)
			{
				if (!string.IsNullOrEmpty(section.Id))
				{
					errorState.Add(new ValidationResult
					{
						Id = "error_" + (errorState.Count + 1),
						Order = errorState.Count + 1,
						Title = $"Section nr {section.Order} Divider has Id!",
						Description = $"Section number {section.Order} is a {section.Type} but has an Id attribute: '{section.Id}'",
						Html = $$"""Section number {{section.Order}} is a {section.Type} but has an Id attribute: '{{section.Id}}'"""
					});
				}

				if (section.Type == ContentSection.SectionType.Setup && section.Order != 1)
				{
					errorState.Add(new ValidationResult
					{
						Id = "error_" + (errorState.Count + 1),
						Order = errorState.Count + 1,
						Title = $"Section nr {section.Order} Setup order!",
						Description = $"Setup section after first position!",
						Html = $$"""Section number {{section.Order}} is a {{section.Type}}! Setup sections must appear only once and before any others."""
					});
				}
			}
			else
			{
				ValidateAttribute(section, section.Id, nameof(ContentSection.Id), section.Title, nameof(ContentSection.Title), ids, errorState);
				ValidateAttribute(section, section.Title, nameof(ContentSection.Title), section.Id, nameof(ContentSection.Id), titles, errorState);
			}
		}

		return TryStoreValidation(errorState, out criticalError);
	}

	/// <summary>
	/// Checks the presence / uniqueness of either Id or Title attributes. Uses the other attribute for reference in the error message.
	/// </summary>
	private static void ValidateAttribute(ContentSection section, string? thisValue, string thisAttributeName,
		string? otherAttributeValue, string otherAttributeName,HashSet<string> seenValues,List<ValidationResult> errorState)
	{
		string insert = string.IsNullOrWhiteSpace(otherAttributeValue) ? "" : $", {otherAttributeName}: '{otherAttributeValue}'";
		string additionalInfo = insert + (string.IsNullOrWhiteSpace(section.Description) ? "" : $", description: '{section.Description}'");

		if (thisValue == null) // null means the attribute isn't just empty, it's not there.
		{
			errorState.Add(new ValidationResult
			{
				Id = "error_" + (errorState.Count + 1),
				Order = errorState.Count + 1,
				Title = $"Section nr {section.Order} missing {thisAttributeName}",
				Description = $"Section number {section.Order}{insert}: is missing the {thisAttributeName} attribute.",
				Html = $$"""Section number {{section.Order}}{{additionalInfo}}"""
			});
		}
		else if (string.IsNullOrWhiteSpace(thisValue))
		{
			errorState.Add(new ValidationResult
			{
				Id = "error_" + (errorState.Count + 1),
				Order = errorState.Count + 1,
				Title = $"Section nr {section.Order} empty {thisAttributeName}",
				Description = $"Section number {section.Order}{insert}: has an empty {thisAttributeName} attribute.",
				Html = $$"""Section number {{section.Order}}{{additionalInfo}}"""
			});
		}
		else if (!seenValues.Add(thisValue.ToLowerInvariant()))
		{
			errorState.Add(new ValidationResult
			{
				Id = "error_" + (errorState.Count + 1),
				Order = errorState.Count + 1,
				Title = $"Section nr {section.Order} duplicate {thisAttributeName}",
				Description = $"Section number {section.Order}{insert}: has a duplicate {thisAttributeName} attribute: '{thisValue}'",
				Html = $$"""Section number {{section.Order}}{{additionalInfo}}"""
			});
		}
	}

	/// <summary> Save the current validation state to disk. Validation errors are visible simply by browsing the site / pressing F5. </summary>
	/// <remarks> Writing to disk is a critical failure, and renders xml validation pointless. The rest of the validation will be dumped, and the
	/// error will be immediately returned to the user. </remarks>
	private bool TryStoreValidation(List<ValidationResult> errorState, out ValidationResult? criticalError)
	{
		bool contentOK = errorState.Count == 0;
		bool saveOK = contentOK
			? file.WriteValidationDate(DateTime.Now.ToUniversalTime())
			: file.WriteErrorState(errorState);

		if (saveOK)
		{
			criticalError = null;
			return true;
		}

		criticalError = contentOK
			? new ValidationResult
			{
				Id = "error",
				Order = 1,
				Title = "Couldn't write validation-date.xml",
				Description = "Failed to write validation-date.xml to disk.",
				Html = "Failed to write validation-date to disk.<br> Check Log. Check directory for permissions / conflicts. Check File for illegal characters."
			} 
			: new ValidationResult
			{
				Id = "error",
				Order = 1,
				Title = "Couldn't write error-state.xml",
				Description = "Failed to write error-state.xml to disk.",
				Html = "Failed to write error-state to disk.<br> Check Log. Check directory for permissions / conflicts. Check File for illegal characters."
			};

		return false;
	}

	private bool ClearValidation()
	{
		bool errorStateCleared = file.DeleteErrorState();
		bool validationDateCleared = file.DeleteValidationDate();
		return errorStateCleared && validationDateCleared;
	}

}