using System.Globalization;
using System.Xml.Linq;
using WebAppBackend.Api.Models;

namespace WebAppBackend.Api.DataAccess;

/// <summary>All code for reading/writing the site-content.xml, error-state.xml and validation-date.xml files. </summary>
/// <remarks>Fun fact: if you rename it to FileAccess, System.Io.FileStream stops working. </remarks>
public class DataAccess (ILogger<DataAccess> logger, IWebHostEnvironment env, IConfiguration configuration) : IDataAccess
{
	private readonly ILogger<DataAccess> _logger = logger;
	private readonly string _siteContentFilePath = ContentPaths.SiteContentFilePath(env, configuration);
	private readonly string _validationDateFilePath = ContentPaths.ValidationDateFilePath(env, configuration);
	private readonly string _errorStateFilePath = ContentPaths.ErrorStateFilePath(env, configuration);

	public bool TouchContentFile(out ValidationResult? error)
	{
		if (!File.Exists(_siteContentFilePath))
		{
			_logger.LogWarning("XML file not found at {Path}", _siteContentFilePath);
			error = new ValidationResult
			{
				Id = "error",
				Order = 1,
				Title = "XML file not found",
				Description = "XML file not found.",
				Html = $"XML file not found at expected folder"
			};
			return false;
		}

		error = null;
		return true;
	}
	
	public List<ContentSection> ReadSiteContent() => ParseSectionsFromFile(_siteContentFilePath);
	public List<ContentSection> ReadErrorState() => ParseSectionsFromFile(_errorStateFilePath);
	public bool ErrorStateExists() => File.Exists(_errorStateFilePath);

	public bool DeleteErrorState()
	{
		try
		{
			if (File.Exists(_errorStateFilePath))
				File.Delete(_errorStateFilePath);
			return true;
		}
		catch (Exception ex)
		{
			_logger.LogError(ex, "Failed to delete error state file at {Path}", _errorStateFilePath);
		}
		return false;
	}

	public bool DeleteValidationDate()
	{
		try
		{
			if (File.Exists(_validationDateFilePath))
				File.Delete(_validationDateFilePath);
			return true;
		}
		catch (Exception ex)
		{
			_logger.LogError(ex, "Failed to delete validation date file at {Path}", _validationDateFilePath);
		}
		return false;
	}

	public DateTime? ValidationDate()
	{
		if (!File.Exists(_validationDateFilePath))
			return null;

		try
		{
			using var stream = new FileStream(_validationDateFilePath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
			var document = XDocument.Load(stream);
			var raw = document.Root?.Value;

			if (DateTime.TryParse(raw, CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind, out var parsed))
			{
				return parsed.ToUniversalTime();
			}

			_logger.LogWarning("Could not parse validation timestamp value '{Value}' in {Path}", raw, _validationDateFilePath);
		}
		catch (Exception ex)
		{
			_logger.LogWarning(ex, "Failed to read validation timestamp from {Path}", _validationDateFilePath);
		}

		return null;
	}

	/// <summary>
	/// Returns the last modified timestamp of the site-content.xml file, or null if the file does not exist.
	/// Has to be UTC because you might be editing the XML file on a local machine with a different time zone than the server.
	/// </summary>
	public DateTime? ContentXmlLastModified()
	{
		if (!File.Exists(_siteContentFilePath))
			return null;

		return File.GetLastWriteTimeUtc(_siteContentFilePath);
	}

	public bool WriteErrorState(List<ValidationResult> errorState)
	{
		try
		{
			var siteElement = new XElement("Site",
				errorState.Select(section => new XElement("Section",
					new XAttribute("id", section.Id ?? string.Empty),
					new XAttribute("title", section.Title ?? string.Empty),
					new XAttribute("type", section.Type.ToString()),
					string.IsNullOrWhiteSpace(section.Description) ? null : new XAttribute("description", section.Description),
					new XElement("Content", new XCData(section.Html ?? string.Empty))
				))
			);

			var document = new XDocument(
				new XDeclaration("1.0", "utf-8", null),
				new XComment(" Auto-generated by ContentValidator when content validation fails. Fix site-content.xml and this file is removed automatically once validation passes again. "),
				siteElement
			);

			document.Save(_errorStateFilePath);
			return true;
		}
		catch (Exception ex)
		{
			_logger.LogError(ex, "Failed to write error state file at {Path}", _errorStateFilePath);
		}
		return false;
	}

	/// <summary>
	/// Writes the validation timestamp to the validation-date.xml file.
	/// Has to be UTC because you don't know where a 3rd party server might be running.
	/// </summary>
	public bool WriteValidationDate(DateTime validatedAtUtc)
	{
		try
		{
			var document = new XDocument(
				new XDeclaration("1.0", "utf-8", null),
				new XElement("ValidationDate", validatedAtUtc.ToUniversalTime().ToString("o"))
			);

			document.Save(_validationDateFilePath);
			return true;
		}
		catch (Exception ex)
		{
			_logger.LogError(ex, "Failed to write validation date file at {Path}", _validationDateFilePath);
		}
		return false;
	}

	private List<ContentSection> ParseSectionsFromFile(string filePath)
	{
		// This a failsafe for when reading error-state. Shouldn't really happen.
		if (!File.Exists(filePath))
		{
			_logger.LogWarning("Content XML file not found at {Path}", filePath);
			return new List<ContentSection>();
		}

		try
		{
			// FileShare.ReadWrite lets someone edit/save the XML file in another
			// program (e.g. Notepad) on Windows without the read here throwing
			// an IOException because the file is "in use".
			using var stream = new FileStream(filePath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
			var document = XDocument.Load(stream, LoadOptions.None);

			var sections = document.Root?
				.Elements("Section")
				.Select((element, index) => new ContentSection
				{
					Id = (string?)element.Attribute("id"),
					Title = (string?)element.Attribute("title"),
					Description = (string?)element.Attribute("description"),
					Order = index + 1, // Avoid falsy 0-based order; start at 1.
					Html = (element.Element("Content")?.Value ?? string.Empty).Trim(),
					Type = ContentSection.TextToType((string?)element.Attribute("type"))
				})
				.ToList();

			return sections ?? new List<ContentSection>();
		}
		catch (Exception ex)
		{
			_logger.LogError(ex, "Failed to read/parse content XML file at {Path}", filePath);
			return new List<ContentSection>()
			{
				new ValidationResult
				{
					Id = "error",
					Order = 1,
					Title = "Failed to parse XML file.",
					Description = "Failed to parse XML file.",
					Html = ""
				}
			};
		}
	}

}